/** Korea Stock Compass v4 - Cloudflare Worker
 * Endpoints: /quotes?codes=005930,000660  /index  /detail?code=005930
 */
const ORIGIN="*";
const H={"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Methods":"GET,OPTIONS","Access-Control-Allow-Headers":"Content-Type","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const num=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(String(v).replace(/,/g,''));return Number.isFinite(n)?n:null};
const headers={"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/126 Safari/537.36","Accept":"application/json, text/plain, */*","Referer":"https://m.stock.naver.com/"};
async function getJson(u){const r=await fetch(u,{headers});if(!r.ok)throw Error(`${r.status} ${u}`);return r.json()}
async function realtime(code){const j=await getJson(`https://polling.finance.naver.com/api/realtime?query=SERVICE_ITEM:${code}`);const areas=j?.result?.areas||[];const area=areas.find(a=>a?.name==='SERVICE_ITEM')||areas[0];const x=area?.datas?.[0];if(!x)throw Error('empty quote');return {code,price:num(x.nv),change:num(x.cr),changeValue:num(x.cv),amount:num(x.aa),volume:num(x.aq),status:x.ms||'',updatedAt:x.localTradedAt||j?.result?.time||null};}
async function basic(code){const j=await getJson(`https://m.stock.naver.com/api/stock/${code}/basic`);return {code,price:num(j.closePrice),change:num(j.fluctuationsRatio),changeValue:num(j.compareToPreviousClosePrice),amount:num(j.accumulatedTradingValue),volume:num(j.accumulatedTradingVolume),status:j.marketStatus||'',updatedAt:j.localTradedAt||null};}
async function quote(code){try{return await realtime(code)}catch(e){try{return await basic(code)}catch(_){return null}}}
async function pool(codes,limit=8){const out=[];let i=0;async function w(){while(i<codes.length){const k=i++;out[k]=await quote(codes[k])}}await Promise.all(Array.from({length:Math.min(limit,codes.length)},w));return out.filter(Boolean)}
async function kospi(){const j=await getJson('https://polling.finance.naver.com/api/realtime?query=SERVICE_INDEX:KOSPI');const a=(j?.result?.areas||[]).find(x=>x?.name==='SERVICE_INDEX')||j?.result?.areas?.[0];const x=a?.datas?.[0];if(!x)throw Error('empty index');return {code:'KOSPI',value:num(x.nv),change:num(x.cr),changeValue:num(x.cv),status:x.ms||'',updatedAt:j?.result?.time||null}}
async function history(code){const j=await getJson(`https://api.stock.naver.com/chart/domestic/item/${code}?periodType=dayCandle`);const a=j?.priceInfos||j?.chartInfo||[];return a.map(x=>({date:x.localDate,close:num(x.closePrice),high:num(x.highPrice),low:num(x.lowPrice),volume:num(x.accumulatedTradingVolume)})).filter(x=>x.close!=null)}
async function integration(code){return getJson(`https://m.stock.naver.com/api/stock/${code}/integration`)}
function sma(a,n){return a.length>=n?a.slice(-n).reduce((x,y)=>x+y,0)/n:null}
function ema(a,n){if(a.length<n)return null;let e=sma(a.slice(0,n),n),k=2/(n+1);for(let i=n;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function rsi(a,n=14){if(a.length<n+1)return null;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){let d=a[i]-a[i-1];if(d>0)g+=d;else l-=d}if(l===0)return 100;return 100-100/(1+(g/n)/(l/n))}
function pct(a,b){return a==null||b==null||!b?null:(a/b-1)*100}
function flatten(o,out={}){if(!o||typeof o!=='object')return out;if(Array.isArray(o)){for(const x of o)flatten(x,out);return out}for(const [k,v] of Object.entries(o)){if(v&&typeof v==='object')flatten(v,out);else if(out[k]===undefined)out[k]=v}return out}
function metric(map,keys){for(const k of keys){if(map[k]!==undefined){const n=num(map[k]);if(n!=null)return n}}return null}
function build(q,j,h){const a=h.map(x=>x.close),last=a.at(-1),m5=sma(a,5),m20=sma(a,20),m60=sma(a,60),e12=ema(a,12),e26=ema(a,26),macd=e12!=null&&e26!=null?e12-e26:null;const prev=a.slice(0,-1),pm=ema(prev,12)!=null&&ema(prev,26)!=null?ema(prev,12)-ema(prev,26):null;const map=flatten(j);const hi=metric(map,['highPriceOf52Weeks','high52WeekPrice'])??Math.max(...h.map(x=>x.high||x.close));const lo=metric(map,['lowPriceOf52Weeks','low52WeekPrice'])??Math.min(...h.map(x=>x.low||x.close));const pos=hi>lo?(last-lo)/(hi-lo)*100:null;const rr=rsi(a),p5=a.length>5?pct(last,a.at(-6)):null,p20=a.length>20?pct(last,a.at(-21)):null;const per=metric(map,['per']),pbr=metric(map,['pbr']),foreign=metric(map,['foreignRate','foreignerHoldRatio']);let trend='중립';if(m5&&m20&&m60){if(last>m5&&m5>m20&&m20>m60)trend='강한 상승';else if(last>m20&&m20>m60)trend='상승';else if(last<m5&&m5<m20&&m20<m60)trend='강한 하락';else if(last<m20&&m20<m60)trend='하락'}const mom=Math.max(0,Math.min(100,50+(p5||0)*2+(p20||0)*.7));const ts=trend==='강한 상승'?100:trend==='상승'?78:trend==='하락'?30:trend==='강한 하락'?15:50;const rs=rr==null?50:(rr>=50&&rr<=70?85:rr>=40?60:rr>70?55:30);const vs=per>0&&per<15&&pbr!=null&&pbr<1.5?80:55;const score=Math.round(mom*.30+ts*.25+rs*.15+vs*.10+(pos??50)*.10+Math.max(0,Math.min(100,50+(q.change||0)*8))*.10);return {ret5:p5,ret20:p20,rsi14:rr,ma5:m5,ma20:m20,ma60:m60,macdSignal:macd==null?'—':macd>0?(pm!=null&&macd>pm?'골든·강화':'양수'):(pm!=null&&macd>pm?'하락 둔화':'음수'),week52Pos:pos,high52:hi,low52:lo,per,pbr,foreignRate:foreign,trend,valuation:vs===80?'매력':'보통',momentum:mom>=65?'강함':mom<=40?'약함':'보통',reason:score>=80?'추세·모멘텀 우수':score>=68?'상승 추세 우위':score<=38?'추세·모멘텀 약화':'중립',score,exchange:j?.stockExchangeType?.name||q.status,updatedAt:q.updatedAt}}
export default {async fetch(req){const u=new URL(req.url);if(req.method==='OPTIONS')return new Response('',{headers:H});try{if(u.pathname==='/index')return new Response(JSON.stringify({ok:true,source:'NAVER Finance realtime',item:await kospi()}),{headers:H});if(u.pathname==='/quotes'){const codes=(u.searchParams.get('codes')||'').split(',').filter(x=>/^\d{6}$/.test(x)).slice(0,50);if(!codes.length)return new Response(JSON.stringify({ok:false,error:'codes required'}),{status:400,headers:H});const items=await pool(codes);return new Response(JSON.stringify({ok:true,source:'NAVER Finance realtime',updatedAt:new Date().toISOString(),count:items.length,items}),{headers:H})}if(u.pathname==='/detail'){const code=u.searchParams.get('code')||'';if(!/^\d{6}$/.test(code))return new Response(JSON.stringify({ok:false,error:'valid 6-digit code required'}),{status:400,headers:H});const q=await quote(code);if(!q)return new Response(JSON.stringify({ok:false,error:'quote unavailable'}),{status:502,headers:H});const [j,h]=await Promise.all([integration(code),history(code)]);const metrics=build(q,j,h);return new Response(JSON.stringify({ok:true,source:'NAVER Finance',quote:q,metrics,score:metrics.score}),{headers:H})}return new Response(JSON.stringify({ok:true,message:'Korea Stock Compass v4',endpoints:['/quotes?codes=005930,000660','/index','/detail?code=005930']}),{headers:H})}catch(e){return new Response(JSON.stringify({ok:false,error:String(e?.message||e)}),{status:502,headers:H})}}}
